export const GET_ARTIST_ITEMS="GET_ARTIST_ITEMS"
export const GET_ARTIST="GET_ARTIST"
export const GET_PLAYLIST_FROM_ARTIST="GET_PLAYLIST_FROM_ARTIST"
export const GET_PLAYLIST_ITEMS_FROM_ARTIST=" GET_PLAYLIST_ITEMS_FROM_ARTIST"
